# SPDX-FileCopyrightText: 2024 Davide Paro <dparo@outlook.it>, et al.
# SPDX-FileContributor: Davide Paro <dparo@outlook.it>
#
# SPDX-License-Identifier: Apache-2.0

format:
  line_width: 80
  tab_size: 4
  use_tabchars: false
  fractional_tab_policy: use-space
  dangle_parens: false
  dangle_align: prefix
  line_ending: unix
  command_case: canonical
  keyword_case: canonical
  always_wrap: []
  enable_sort: true
