# SPDX-FileCopyrightText: 2024 Davide Paro <dparo@outlook.it>, et al.
# SPDX-FileContributor: Davide Paro <dparo@outlook.it>
#
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
        - id: reuse
          name: Verify presence of SPDX License
          args: [lint]

  # - repo: https://github.com/cmake-lint/cmake-lint
  #   rev: 1.4.2
  #   hooks:
  #     - id: cmakelint

  - repo: local
    hooks:
    - id: cmake
      name: Build and test project with ASAN
      description: Build and test project with ASAN
      entry: cmake --workflow --preset debug-asan
      language: 'system'
      exclude: README.md
      pass_filenames: false

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
      - id: clang-tidy
      - id: cppcheck
        args: [-q, --error-exitcode=1, --enable=all, "--suppress=unmatchedSuppression", "--suppress=missingIncludeSystem", "--suppress=missingInclude", "--suppress=unusedFunction"]
      # - id: cpplint
      # - id: include-what-you-use
