# SPDX-FileCopyrightText: 2024 Davide Paro <dparo@outlook.it>, et al.
# SPDX-FileContributor: Davide Paro <dparo@outlook.it>
#
# SPDX-License-Identifier: Apache-2.0

# This file describes the licensing and copyright situation for files that
# cannot be annotated directly, for example because of being simply
# uncommentable. Unless this is the case, a file should be annotated directly.
#
# This follows the REUSE specification: https://reuse.software/spec-3.2/#reusetoml

version = 1

[[annotations]]
path = [
    "vcpkg.json",
    "vcpkg-configuration.json",
    "CMakePresets.json",
    ".cmakelintrc",
]
SPDX-FileCopyrightText = "Davide Paro <dparo@outlook.it>, et al."
SPDX-License-Identifier = "Apache-2.0"
# If there is licensing/copyright information in or next to these files, prefer that
precedence = "closest"
