version: "3"

# TODO(d.paro): Complete this file

interval: 500ms

vars:
  PRESET: '{{.PRESET | default "debug-asan"}}'
  PORT: '{{.PORT | default 3000}}'
  HOST: '{{.HOST | default "127.0.0.1"}}'


tasks:
  assets-build:
    cmds:
      - pnpm exec tailwindcss --input input.css -o output.css --optimize --minify

  assets-watch:
    cmds:
      - pnpm exec tailwindcss --input input.css -o output.css --optimize --watch

  configure:
    cmds:
      - cmake --preset {{.PRESET}}

  build:
    cmds:
      - cmake --build --preset={{.PRESET}}

  serve:
    deps:
      # - assets-build
      - build

    cmds:
      # - gdbserver --once --no-startup-with-shell 127.0.0.1:10000 ./build/{{.PRESET}}/src/chaddy --host {{.HOST}} -p {{.PORT}}
      - ./build/{{.PRESET}}/src/chaddy --host {{.HOST}} -p {{.PORT}}

  serve:watch:
    watch: true
    sources:
      - '**/CMakeLists.txt'
      - 'src/**/*.c'
      - 'src/**/*.h'
      - '**/*.css'
      - '**/*.html'
    deps:
      - serve

